pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.minecraftforge.net/" }
        maven { url = "https://maven.neoforged.net/" }
        mavenCentral()
        mavenLocal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = "https://jitpack.io" }
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url = "https://redempt.dev" }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = "https://maven.neoforged.net/releases" }
        exclusiveContent {
            forRepository { maven { url = "https://api.modrinth.com/maven" } }
            filter { includeGroup "maven.modrinth" }
        }
    }
}

rootProject.name = 'Visor'
include 'visor-core','visor-neoforge','visor-api'
include 'visor-api:neoforge'
findProject(':visor-api:neoforge')?.name = 'neoforge'
include 'visor-core:stubs'
findProject(':visor-core:stubs')?.name = 'stubs'

