

[versions]
#Gradle Addons
shadow              = "8.1.1"
architectury        = "3.4-SNAPSHOT"
architectury-loom   = "1.11-SNAPSHOT"
loom-quiltflower    = "1.8.0"


#Annotations
lombok                 = "1.18.46"
jetbrains              = "26.1.0"

#Core
minecraftVersion       = "1.21.1"
parchment              = "2024.11.17"
lwjgl                  = "3.3.6"
atum-vr                = "1.13.0beta"
atum-config            = '1.2.0pre3'

mixinExtras            = "0.4.1"

#NeoForge
neoforge               = "21.1.247"

#Other mods
mods_sodium                 = "mc1.21.1-0.8.12-neoforge"
mods_iris                   = "1.8.12+1.21.1-neoforge"


[plugins]
architectury         = { id = "architectury-plugin",            version.ref = "architectury" }
architectury-loom    = { id = "dev.architectury.loom",          version.ref = "architectury-loom" }
loom-quiltflower     = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom-quiltflower" }
shadow               = { id = "com.github.johnrengelman.shadow",  version.ref = "shadow" }


[libraries]

# Annotations
lombok           = { module = "org.projectlombok:lombok",           version.ref = "lombok" }
jetbrains        = { module = "org.jetbrains:annotations",         version.ref = "jetbrains" }

# Core
lwjgl-openxr       = { module = "org.lwjgl:lwjgl-openxr",           version.ref = "lwjgl" }
atumvr-api         = { module = "com.github.Phoenix-Ra.AtumVR:atumvr-api",     version.ref = "atum-vr"}
atumvr-core        = { module = "com.github.Phoenix-Ra.AtumVR:atumvr-core",    version.ref = "atum-vr"}
atumvr-config      = { module = "com.github.Phoenix-Ra:AtumConfiguration",    version.ref = "atum-config"}

#Other Mods
mod-sodium = { module = "maven.modrinth:sodium",  version.ref = "mods_sodium"}
mod-iris   = { module = "maven.modrinth:iris",    version.ref = "mods_iris"}

[bundles]
annotations        = [ "lombok", "jetbrains" ]


