architectury {

    common(rootProject.enabled_platforms.split(","))
}
loom{
    accessWidenerPath = file("src/main/resources/visor.accesswidener")
}
dependencies {
    // net.neoforged.api.distmarker.OnlyIn/Dist (replaces fabric @Environment)
    compileOnly "net.neoforged:mergetool:2.0.0:api"

    // ---- LOCAL DEPENDENCY
    modApi name: 'atumvr-api-1.14.0beta-snapshot#14'
    modApi name: 'atumvr-core-1.14.0beta-snapshot#14'
    // ----
    //api(libs.atumvr.api)
    //api(libs.atumvr.core)
    api(libs.atumvr.config)

    compileOnly(libs.bundles.annotations)
    annotationProcessor(libs.bundles.annotations)
}