modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPLv3"

[[mods]]
modId = "visor"
version = "${version}"
displayName = "Visor"
logoFile = "assets/visor/icon.png"
authors = "PhoenixRa"
displayTest = "NONE"
description = '''
The VR mod that is built to support addons

'''

[[dependencies.visor]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.visor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "AFTER"
side = "BOTH"